import { CalendarDays, ArrowRightLeft, TrendingUp, Clock } from 'lucide-react';

export const DIMENSIONS = [
  { id: 'd1', name: '按日', category: '日期信息' },
  { id: 'd2', name: '按周', category: '日期信息' },
  { id: 'd3', name: '按月', category: '日期信息' },
  { id: 'd4', name: '店铺编号', category: '店铺信息' },
  { id: 'd5', name: '店铺名称', category: '店铺信息' },
  { id: 'd6', name: '区域', category: '店铺信息' },
  { id: 'd7', name: '大区', category: '店铺信息' },
  { id: 'd8', name: '督导', category: '店铺信息' },
  { id: 'd9', name: '考核门店区分', category: '店铺信息' },
  { id: 'd10', name: '店铺类型', category: '店铺信息' },
  { id: 'd11', name: '直营加盟类型', category: '店铺信息' },
  { id: 'd12', name: '既存店区分', category: '店铺信息' },
  { id: 'd13', name: '开店日期', category: '店铺信息' },
  { id: 'd14', name: '闭店日期', category: '店铺信息' },
  { id: 'd15', name: '店铺状态', category: '店铺信息' },
  { id: 'd16', name: '营业面积', category: '店铺信息' },
  { id: 'd17', name: '员工人数', category: '店铺信息' },
  { id: 'd18', name: '大类编码', category: '分类信息' },
  { id: 'd19', name: '大类名称', category: '分类信息' },
  { id: 'd20', name: '中类编码', category: '分类信息' },
  { id: 'd21', name: '中类名称', category: '分类信息' },
  { id: 'd22', name: '小类编码', category: '分类信息' },
  { id: 'd23', name: '小类名称', category: '分类信息' },
  { id: 'd24', name: '品类经理', category: '分类信息' },
  { id: 'd25', name: '采购助理', category: '分类信息' },
  { id: 'd26', name: '供应商编码', category: '供应商信息' },
  { id: 'd27', name: '供应商名称', category: '供应商信息' },
  { id: 'd28', name: '商品编码', category: '商品信息' },
  { id: 'd29', name: '商品名称', category: '商品信息' },
  { id: 'd30', name: '商品条码', category: '商品信息' },
  { id: 'd31', name: '新品标识', category: '商品信息' },
  { id: 'd32', name: '可订标识', category: '商品信息' },
];

export const METRICS = [
  { id: 'm1', name: '销售额', category: '销售' },
  { id: 'm2', name: '毛利额', category: '销售' },
  { id: 'm3', name: '销售额PSD', category: '销售' },
  { id: 'm4', name: '毛利率', category: '销售', unit: '%' },
  { id: 'm5', name: '动销率', category: '销售', unit: '%' },
  { id: 'm6', name: '动销率', category: '销售', unit: '%' },
  { id: 'm7', name: '周转天数', category: '库存' },
  { id: 'm8', name: '库存金额(期初)', category: '库存' },
  { id: 'm9', name: '库存金额(期末)', category: '库存' },
  { id: 'm10', name: '库存数量(期初)', category: '库存' },
  { id: 'm11', name: '库存数量(期末)', category: '库存' },
  { id: 'm12', name: '库存数量(日均)', category: '库存' },
  { id: 'm13', name: '库存金额(日均)', category: '库存' },
  { id: 'm14', name: '订货数量', category: '进货' },
  { id: 'm15', name: '订货数量PSD', category: '进货' },
];

export const SCENARIOS = [
  { id: 'query', name: '期间查询', icon: CalendarDays },
  { id: 'compare', name: '期间对比', icon: ArrowRightLeft },
  { id: 'trend', name: '期间趋势', icon: TrendingUp },
  { id: 'time', name: '时段查询', icon: Clock },
];

export const DIM_DICT = {
  '按日': ['20260101', '20260102', '20260103', '20260104', '20260105', '20260106', '20260107', '20260108','20260109','20260110','20260111','20260112'],
  '按周': ['2026w1', '2026w2', '2026w3', '2026w4', '2026w5', '2026w6', '2026w7', '2026w8'],
  '按月': ['202601', '202602', '202603', '202604', '202605', '202606', '202607', '202608','202609','202610','202611','202612'],
  '店铺名称': ['门店一', '门店二', '门店三', '门店四', '门店五', '门店六', '门店七', '门店八'],
  '店铺编号': ['001', '002', '003', '004', '005', '006', '007', '008'],
  '店铺类型': ['直营店', '加盟店'],
  '督导': ['张三', '李四', '王五', '赵六'],
  '考核门店区分': ['考核门店', '非考核门店'],
  '既存店区分': ['既存店', '非既存店'],
  '大类编码': ['A001', 'A002', 'A003', 'A004', 'A005', 'A006'],
  '中类编码': ['B001', 'B002', 'B003', 'B004', 'B005', 'B006'],
  '小类编码': ['C001', 'C002', 'C003', 'C004', 'C005', 'C006'],
  '中类名称': ['食品饮料', '日用百货', '家用电器', '服装鞋帽', '美妆个护', '母婴用品'],
  '小类名称': ['生鲜食品', '休闲零食', '酒水饮料', '日用百货', '家用电器', '美妆个护'],
  '大区': ['华东大区', '华南大区', '华北大区', '西南大区', '西北大区', '东北大区', '华中大区'],
  '区域': ['上海市', '北京市', '广州市', '深圳市', '杭州市', '成都市', '武汉市', '南京市'],
  '大类名称': ['生鲜食品', '休闲零食', '酒水饮料', '日用百货', '家用电器', '美妆个护'],
  '全店销量ABC级别': ['A类 (头部20%)', 'B类 (腰部30%)', 'C类 (尾部50%)'],
  '商品名称': ['可口可乐330ml', '伊利纯牛奶250ml', '农夫山泉500ml', '乐事薯片原味'],
  '默认': ['选项1', '选项2', '选项3', '选项4']
};
